apiVersion: apps/v1
kind: Deployment
metadata:
  name: federatorai-operator
  namespace: federatorai
  labels:
    name: federatorai-operator
    app: Federator.ai
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: federatorai-operator
  template:
    metadata:
      labels:
        name: federatorai-operator
        app: Federator.ai
    spec:
      securityContext:
        fsGroup: 1001
      serviceAccountName: federatorai-operator
      initContainers:
        - name: upgrader
          image: quay.io/prophetstor/federatorai-operator-ubi:latest
          command:
          - federatorai-operator
          args:
          - "upgrade"
          env:
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: FEDERATORAI_OPERATOR_INFLUXDB_ADDRESS
              value: ""
            - name: FEDERATORAI_OPERATOR_INFLUXDB_SERVICE_NAME
              value: alameda-influxdb
            - name: FEDERATORAI_OPERATOR_INFLUXDB_SERVICE_PORT
              value: "8086"
            - name: FEDERATORAI_OPERATOR_INFLUXDB_USERNAME
              value: admin
            - name: FEDERATORAI_OPERATOR_INFLUXDB_PASSWORD
              value: adminpass
          volumeMounts:
          - mountPath: /var/log/alameda
            name: log
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      containers:
        - name: federatorai-operator
          # Replace this with the built image name
          image: quay.io/prophetstor/federatorai-operator-ubi:latest
          imagePullPolicy: IfNotPresent
          command:
          - federatorai-operator
          env:
            - name: NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "federatorai-operator"
          readinessProbe:
            failureThreshold: 20
            httpGet:
              path: /readyz
              port: 8083
            initialDelaySeconds: 5
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 5
          volumeMounts:
          - mountPath: /var/log/alameda
            name: log
          - mountPath: /tmp/k8s-webhook-server/serving-certs
            name: cert
            readOnly: true
      volumes:
        - name: log
          emptyDir: {}
        - name: cert
          secret:
            defaultMode: 420
            secretName: federatorai-operator-service-cert
