kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: federatorai-operator
  namespace: federatorai
subjects:
- kind: ServiceAccount
  name: federatorai-operator
  namespace: federatorai
roleRef:
  kind: Role
  name: federatorai-operator
  apiGroup: rbac.authorization.k8s.io
