apiVersion: v1
kind: Service
metadata:
  labels:
    component: federatorai-operator
  name: federatorai-operator-service
  namespace: federatorai
spec:
  ports:
  - port: 443
    targetPort: 50443
  selector:
    name: federatorai-operator
    app: Federator.ai