---
- hosts: localhost
  tasks:
    - name: Includ user vars
      include_vars: "user_variable.yaml"

    - name: Includ default vars
      include_vars: "default_variable.yaml"

    - name: Check all variables
      include: check_variables.yaml

    - name: Check environment
      include: check_env.yaml

    - name: Install operator
      include: install_operator.yaml

    - name: Print msg
      debug:
        msg: "Install Federator.ai operator {{ federatorai_version }} successfully!"

    - name: Upgrade alamedaservice
      include: upgrade_alamedaservice.yaml
      when: (previous_alamedaservice_name != "")

    - name: Install alamedaservice
      include: install_alamedaservice.yaml
      when: (previous_alamedaservice_name == "")

    # - name: Setup cluster alamedascaler
    #   include_tasks: setup_cluster_alamedascaler.yaml

    - name: Print msg
      debug:
        msg: "Install Federator.ai {{ federatorai_version }} successfully!"
